services:
  postgres:
    image: postgres:16
    container_name: mf_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mondi
      POSTGRES_PASSWORD: mondi
      POSTGRES_DB: mondi_food
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: mf_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: mondifood@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data:
