spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mondi_food
    username: mondi
    password: mondi
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  name: Mondi-Food
  env: dev
